### ISSUE TITLE
Handle no inquiries state

### ISSUE THREAD

**Issue by l2succes** [artsy/reaction-force#101]
Should we display a message when the user has no inquiries

![screen shot 2017-04-17 at 10 26 49 am](https://cloud.githubusercontent.com/assets/296775/25091704/84a2ba0a-2358-11e7-95dc-cce3f98f7a46.png)

**Comment by mzikherman** [comment]
Good question! I think we'd only be sending the email to users who have had inquiries, but yea we should probably have _something_ for this case.

@briansw thoughts?

**Comment by briansw** [comment]
@mzikherman that's right. This will only go out to users who have made at least one inquiry so I don't think this should be a problem. @tayapage6 seem ok to you to not address this state given this?

**Comment by alloy** [comment]
Yeah my understanding was that people in this state wouldn’t get an email. I’m gonna close for now, but @tayapage6 can re-open in case this is needed after all.
