### ISSUE TITLE
Fix "Invalid email and password" handling on Login Page

### ISSUE THREAD

**Issue by l2succes** [artsy/reaction-force#123]
As of now if logging in fails the user is redirected to this page which shouldn't happen
<img width="1426" alt="screen shot 2017-04-20 at 10 37 39 am" src="https://cloud.githubusercontent.com/assets/296775/25236252/67978b16-25b5-11e7-80df-c5751d2b7ece.png">

**Comment by alloy** [comment]
When I tried to sign in with Twitter, I got redirected and was faced with this:

![screen shot 2017-04-22 at 22 39 29](https://cloud.githubusercontent.com/assets/2320/25308044/c7fe60e4-27ac-11e7-92a2-95939dacb30a.png)

**Comment by l2succes** [comment]
Fixed.
