### ISSUE TITLE
[Relay] Our setup breaks when unauthenticated.

### ISSUE THREAD

**Issue by alloy** [artsy/reaction-force#153]
E.g. visiting this page shows 0 results when not signed-in: https://staging.artsy.net/tag/dog/artworks

![screen shot 2017-05-10 at 13 52 03](https://cloud.githubusercontent.com/assets/2320/25897746/648616de-3589-11e7-88b3-66c8c83d6256.png)

**Comment by alloy** [comment]
Well this is interesting. [This code](https://github.com/artsy/reaction-force/blob/8d6f0852421837482d78b8fd637cd26f52644800/src/relay/config.ts#L4-L11):

```ts
export function artsyNetworkLayer(user?: User) {
  return new Relay.DefaultNetworkLayer(sharify.data.METAPHYSICS_ENDPOINT, {
    headers: !!user ? {
      "X-USER-ID": user.id,
      "X-ACCESS-TOKEN": user.accessToken,
    } : {},
  })
}
```

Gets compiled to:

```js
            function artsyNetworkLayer(user) {
                return new (_get__("Relay").DefaultNetworkLayer)(_get__("sd").METAPHYSICS_ENDPOINT,{
                    headers: !_get__("sd").CURRENT_USER ? {
                        "X-USER-ID": _get__("sd").CURRENT_USER.id,
                        "X-ACCESS-TOKEN": _get__("sd").CURRENT_USER.accessToken
                    } : {}
                })
            }
```

The issue is that the double bang is turned into a single bang, leading to the wrong code being taken.

🤔

**Comment by alloy** [comment]
The compiled code that’s in the reaction-force package looks like this:

```js
function artsyNetworkLayer(user) {
    return new Relay.DefaultNetworkLayer(sharify.data.METAPHYSICS_ENDPOINT, {
        headers: !!user ? {
            "X-USER-ID": user.id,
            "X-ACCESS-TOKEN": user.accessToken
        } : {}
    });
}
```

Meaning that some other bundler thing is rewriting that code.

`_get__` looks to be part of a ‘rewire’ package. Not sure if that’s the cause of rewriting the double into a single bang, but I do wonder what we have a ‘rewire’ package for in production at all?

@craigspaeth @broskoski does any of this ring any bells?

**Comment by broskoski** [comment]
Hm, vaguely. Will look at what's going on over there.

**Comment by alloy** [comment]
Ok, thanks 👍
