### ISSUE TITLE
[webpack] We’re not shipping React builds optimised for production.

### ISSUE THREAD

**Issue by alloy** [artsy/reaction-force#154]
![screen shot 2017-05-10 at 13 55 41](https://cloud.githubusercontent.com/assets/2320/25897762/84ecc5da-3589-11e7-886e-89c8f23fd3f3.png)

https://facebook.github.io/react/docs/optimizing-performance.html#webpack

**Comment by alloy** [comment]
In retrospect, it looks like reaction-force does bundle React the correct way, for its full app/pages, so it must be the React that Force imports.

**Comment by xtina-starr** [comment]
@alloy what extension is that you are using?

**Comment by alloy** [comment]
The React Dev Tools https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi

**Comment by xtina-starr** [comment]
@alloy sweet!
