### ISSUE TITLE
Loyalty Program landing page 'program benefits' component

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction-force#3]
This will be shown to NY ACBs and NY 3Ws, just static HTML.

<img width="353" alt="screen shot 2017-02-14 at 12 52 51 pm" src="https://cloud.githubusercontent.com/assets/1457859/22941681/79c4e1e6-f2b4-11e6-9418-84bf82d5da77.png">

See https://github.com/artsy/collector-experience/issues/86#issuecomment-278797200 (Landing Page) section

**Comment by xtina-starr** [comment]
This will actually be the email and not the landing page.

**Comment by mzikherman** [comment]
My favorite kind of issue closing- w/o even having to do anything.
