### ISSUE TITLE
Loyalty program landing page component

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction-force#4]
Landing page, + optionally including 'program benefits' component

Design: https://artsy.wake.com/1492

https://github.com/artsy/collector-experience/issues/86#issuecomment-278797200 (Landing Page section)

**Comment by alloy** [comment]
How does this differ from #3?

**Comment by mzikherman** [comment]
I guess this is an email now? So it doesn't matter, but I intended the 'program benefits' component to be the one that renders (or not), based on the user type, and then this was the container that included that, and the other static components that are present for all users.
