### ISSUE TITLE
Loyalty Program landing page button that triggers login modal

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction-force#5]
This should pop up the login modal, before taking the user to the next page (where they view old inquiries).

Does this mean we should build not just the button as a component here, but also the whole login modal?

<img width="772" alt="screen shot 2017-02-14 at 1 04 53 pm" src="https://cloud.githubusercontent.com/assets/1457859/22942111/26c65aa4-f2b6-11e6-834a-ad1bad43e128.png">

https://github.com/artsy/collector-experience/issues/86#issuecomment-278797200 (Authentication section)

**Comment by alloy** [comment]
> Does this mean we should build not just the button as a component here, but also the whole login modal?

Nah, I’d like to use the existing one. Can’t we just send the user there and set a referrer URL that the user gets redirected back to after authentication?

**Comment by mzikherman** [comment]
Yea, but we would need to require the user to do a whole other page load, whereas I think ideally the button just triggers the modal.

What we _could_ do w/o building it here is have the button, if not logged-in, link you to something like: `https://www.artsy.net/log_in?redirect-to=/artists` (replace the `redirect-to` with whatever the next step route will be). That will load the home page, _and_ pop up the log in modal, which would also then redirect you.

**Comment by mzikherman** [comment]
I'm not sure how else to trigger the modal besides that server-side thing ^, so while it would work, it is a whole other page load, as well as having the home page in the background, so I think it's probably not ideal.

**Comment by 1aurabrown** [comment]
switched this to 'needs detail' given the conversation above

**Comment by mzikherman** [comment]
Done, we have the redirect/standalone page.
