### ISSUE TITLE
Missing a bundle in Force prod

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction-force#57]
<img width="921" alt="screen shot 2017-03-27 at 6 24 42 pm" src="https://cloud.githubusercontent.com/assets/1457859/24380658/81b87f62-131a-11e7-9479-f55b2c7326de.png">

Seems like it's trying to request https://www.artsy.net/bundles/inquiries.js

**Comment by alloy** [comment]
Fixed by #99.
