### ISSUE TITLE
Typo in /inquiries page in loyalty app

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction-force#58]
![pasted image at 2017_03_27 06_21 pm](https://cloud.githubusercontent.com/assets/1457859/24380890/9826b79a-131b-11e7-845c-aed8fa8ade8c.png)

**you** purchased

**Comment by alloy** [comment]
This is done.

**Comment by oxaudo** [comment]
It's a lot of pleases in this 2 lines of text:)

**Comment by alloy** [comment]
We aim to please!

But in all seriousness, I agree with you, however these two sentences are normally not shown back to back as there would be actual inquired upon artworks in between the two.
