### ISSUE TITLE
Express session misconfigured in production environments

### ISSUE THREAD

**Issue by izakp** [artsy/reaction-force#59]
`express-session` might well be the cause of Force memory leaks.  When starting up Force, we get this output:

```
express-session deprecated undefined resave option; provide resave option node_modules/reaction-force/dist/apps/loyalty/server/index.js:20:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option node_modules/reaction-force/dist/apps/loyalty/server/index.js:20:9
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```

https://github.com/expressjs/session even has this warning in their README.  https://github.com/expressjs/session#sessionoptions

We should use another compatible session store in production, such as `connect-redis` and https://github.com/expressjs/session#compatible-session-stores

cc @mzikherman @alloy

**Comment by mzikherman** [comment]
To be fair, this pretty damning chart:

![pasted image at 2017_03_27 05_49 pm](https://cloud.githubusercontent.com/assets/1457859/24382678/e35a4eb6-1325-11e7-9fa4-f5a2649e8e0e.png)

seems to point to something in https://github.com/artsy/force/pull/1076 , (which doesn't appear to have anything suspicious).

This `reaction-force` dependency in Force was also only deployed earlier today, so I think it's unlikely to be the culprit with any issues in Force.

However, we should definitely fix this so thank you for the report, sir.
