### ISSUE TITLE
Inquiry List Artwork Brick

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction-force#6]
Discuss with @broskoski about consolidation, this is a brick to be shown that represents your inquiry on the work.

<img width="573" alt="screen shot 2017-02-14 at 1 25 52 pm" src="https://cloud.githubusercontent.com/assets/1457859/22942823/14dab792-f2b9-11e6-905f-77f9fe50639f.png">

https://github.com/artsy/collector-experience/issues/86#issuecomment-278797200 (Inquiries section)

**Comment by xtina-starr** [comment]
This was finished in https://github.com/artsy/reaction-force/pull/61 and later refactor in https://github.com/artsy/reaction-force/pull/73
