### ISSUE TITLE
Babel error unless .babelrc file is present

### ISSUE THREAD

**Issue by sarahscott** [artsy/reaction-force#60]
Seems to be fixed if [this file](https://github.com/artsy/reaction-force/pull/51/files#diff-e56633f72ecc521128b3db6586074d2c) is added.

<img width="1058" alt="screen shot 2017-03-28 at 3 12 24 pm" src="https://cloud.githubusercontent.com/assets/2712962/24408716/b453fa32-13ce-11e7-82e7-f50807f31d88.png">

**Comment by yuki24** [comment]
Now we have `.babelrc` and it works fine. Should we close this issue?

**Comment by alloy** [comment]
Yup 👍
