### ISSUE TITLE
Loyalty Program 'repeat visitor' page

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction-force#66]
Very similar to the 'Thank you' page, when the user returns after already submitting their registration, we show them a confirmation page.

https://cloud.githubusercontent.com/assets/1022172/23515188/6c4be048-ff37-11e6-974d-880d7ca86772.jpg

This requires https://github.com/artsy/gravity/issues/10917 to be done (so that the page can tell if a user already submitted).

**Comment by mzikherman** [comment]
This means we'll need to fetch the user's collector profile when loading the page (in order to see whether or not they are a `loyalty_applicant`).

**Comment by mzikherman** [comment]
Somewhere here is maybe where we'd do that? https://github.com/artsy/reaction-force/blob/a72aa3fe4bd9280057860c24af246226f43a40a4/src/apps/loyalty/server/index.tsx#L67-L72

**Comment by yuki24** [comment]
finished in #64.
