### ISSUE TITLE
When a user selects an artwork purchase, update its conversation buyer_outcome

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction-force#68]
On the selection of an inquiry artwork, mutate its conversation and set `buyer_outcome` to 'purchased'

cc @xtina-starr I think we may want to do this on the action of selecting an artwork. Should definitely be after your initial PR on that for sure, maybe we can pair on this?

It'll be using the metaphysics mutation, and it'll need access to the `impulse_conversation_id` from the inquiry request fetch (in order to update that conversation).

**Comment by mzikherman** [comment]
Assigning you @l2succes as discussed, gettin' some Relay mutations in!

**Comment by l2succes** [comment]
Done!
