### ISSUE TITLE
Inquiry List Grid

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction-force#7]
This should probably happen after https://github.com/artsy/reaction-force/issues/6.

This is a grid (not masonry) of historical inquiries/bricks. 

https://github.com/artsy/collector-experience/issues/86#issuecomment-278797200 (Inquiry section)

**Comment by mzikherman** [comment]
This grid should also be able to support pagination/inf scroll. The design calls for a sticky header, and you scroll thru all your inquiries (which will be a paginated Metaphysics interface: https://github.com/artsy/metaphysics/issues/549).

Not sure if 'pagination' of this grid is an independent component or just part of it.

**Comment by alloy** [comment]
This is done.
