### ISSUE TITLE
Inquiry Marked as Purchase overlay

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction-force#8]
User should be able to click on an historical inquiry brick and 'mark' it as a purchase.

- Shows purple check overlay
- Makes request to Impulse to mark the conversation with the appropriate outcome

This depends on an Auth update to Impulse: https://github.com/artsy/impulse/issues/195

**Comment by alloy** [comment]
After some discussion with @1aurabrown and @ashkan18, it appears we do not need to POST any data to Impulse ourselves. Instead:

1. We update [the `user_reported_outcome` field](https://github.com/artsy/gravity/blob/7729282b69a8a3d7873c450eac0977e7fd617087/app/models/domain/inquiry_request.rb#L97) of an inquiry to be `purchased`.
2. Gravity automatically sends that update to Impulse.
3. The CR team gets a notification about that self-reported outcome, they vet it, and eventually mark the official outcome of the inquiry as `sold`.

So we really only need to do step 1.

**Comment by ashkan18** [comment]
Also note the issue @mzikherman had originally, I think ideally we'd do auth in Impulse and then call Impulse directly from Force but we can do that in a separate task if we want to proceed with this feature.

**Comment by mzikherman** [comment]
FWIW I'd be down to do things the 'right' way from the start, if it makes sense. Most of this code is new tech/new repo so it's greenfield and so maybe we _can_ do it 'properly' (aka directly to Impulse, and not use Gravity as a 'broker').

**Comment by joeyAghion** [comment]
I think it's possible to satisfy these specific requirements from existing [or slightly modified] APIs, but we are actively trying to shift the authority about these models from Gravity to Impulse. We've already accomplished this for inquiries/conversations from partners' perspective.

It would be a step back to build new collector inquiry features around the old APIs and models. (In many ways, the Impulse modeling better reflects our more recent understanding of inquiries as ongoing conversations that can result in purchases, invoices, etc.)

**Comment by alloy** [comment]
Let’s definitely do whatever the current preferred way is.

Does this also change in any way how we should be fetching inquiry data or should we stil do that through the existing Gravity endpoints? https://github.com/artsy/metaphysics/issues/549

**Comment by ashkan18** [comment]
What data from inquiry request we need?

**Comment by mzikherman** [comment]
Assigning this to you @xtina-starr since its just the overlay 'selected' state now. I'll make the Impulse update its own issue.

**Comment by alloy** [comment]
This is done.
