### ISSUE TITLE
Be able to stay logged in with artsy passport

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction-force#81]

**Comment by alloy** [comment]
Is this referring to a session made from Force?

**Comment by l2succes** [comment]
No, that's referring to dev mode. As of now, the session gets reset whenever we make a change to any component via HMR. I just have to enable cookies in development

The session is persisted within force and getting picked up correctly in the sub app.

**Comment by alloy** [comment]
Ah gotcha, thanks for the great explanation 👌
