### ISSUE TITLE
Auto-enroll ACBs and skip the inquiries step

### ISSUE THREAD

**Issue by mzikherman** [artsy/reaction-force#84]
ACBs (since they are already confirmed) don't need to flag any purchases.

Instead, once they are logged in, they are 'auto-enrolled' and immediately just shown the Thank you page.

'Auto-enrolling' means setting the `loyalty_applicant: true` stuff, and checking if someone is an ACB means fetching `me { collector_profile { confirmed_buyer_at } }` (may need to add it to Metaphysics, but it's already in Gravity).

**Comment by mzikherman** [comment]
As an FYI here's that example: https://github.com/artsy/reaction-force/pull/85

**Comment by alloy** [comment]
Great ticket, will do, sir 👍

**Comment by mzikherman** [comment]
stealin' this in favor of analytics for now...

**Comment by alloy** [comment]
This is done #89
