### ISSUE TITLE
Fonts broken in storybook mode

### ISSUE THREAD

**Issue by broskoski** [artsy/reaction-force#91]
Both icons and our typefaces

**Comment by broskoski** [comment]
Kinda brings me back to an issue I brought up a few days ago....how do people feel about keeping this repo as strictly client-side components (instead of trying to export apps from here as well).

**Comment by alloy** [comment]
I think we should talk about that in a retrospective once we've shipped the first loyalty pages.

**Comment by alloy** [comment]
This got fixed in #97.
